name: Auto request changes

on:
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jonathan016/auto-request-changes-action@v1
      if: contains(github.head_ref, 'feature/') || contains(github.head_ref, 'bugfix/')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
